const dataBase = {
  users: [
    {
      id: 1,
      name: "test user",
      email: "test@test.test",
      password: 1,
      sessions: [],
      imgu: "https://firebasestorage.googleapis.com/v0/b/words-d2019.appspot.com/o/avatars%2Fav1.png?alt=media&token=d83bc75a-2744-49c2-b961-93c631c4351f",
    },
  ],
  user: {
    id: "",
    name: "",
  },

  expressionsList: [
    {
      id: 1,
      stage: 7,
      expression: "Der Rock",
      phrase: "Ihr Rock ist total altmodisch.",
      nextDate: new Date(),
      history: [
        { action: "add", date: new Date("2022-04-20") },
        { action: "read by the plan", date: new Date("2022-04-20") },
        { action: "read by the plan", date: new Date("2022-04-21") },
        { action: "read by the plan", date: new Date("2022-04-22") },
        { action: "read by the plan", date: new Date("2022-04-23") },
        { action: "read by the plan", date: new Date("2022-04-24") },
        { action: "read by the plan", date: new Date("2022-04-25") },
        { action: "read by the plan", date: new Date("2022-04-26") },
      ],
    },
    {
      id: 2,
      stage: 1,
      expression: "die Mütze",
      phrase: "Das ist deine neue Mütze, Schatz.",
      nextDate: new Date("2022-05-01"),
      history: [
        { action: "add", date: new Date("2022-04-30") },
        { action: "read by the plan", date: new Date("2022-04-30") },
      ],
    },
    {
      id: 3,
      stage: 0,
      expression: "Das Hemd",
      phrase: "Mir gefällt dieses Hemd",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 4,
      stage: 0,
      expression: "Der Badeanzug",
      phrase: "Wo finde ich einen Badeanzug?",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 44,
      stage: 0,
      expression: "Der Anzug",
      phrase: "Ich brauche einen Anzug.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 45,
      stage: 0,
      expression: "Das Kleid",
      phrase: "das Kleid ist rot.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 5,
      stage: 0,
      expression: "I think",
      phrase: "I think he is taller than you, but I can’t be certain.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 6,
      stage: 0,
      expression: "I guess",
      phrase: "I guess she prefers roses.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 7,
      stage: 0,
      expression: "Not sure",
      phrase: "I’m not sure we should eat this meal.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 8,
      stage: 0,
      expression: "Not quite sure",
      phrase:
        "Anna explained the task but I’m not quite sure they understood her.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 81,
      stage: 0,
      expression: "Probably",
      phrase: "This is probably the rarest mineral in the world.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 82,
      stage: 0,
      expression: "I’m positive",
      phrase: "I’m positive I left my wallet in my car.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 83,
      stage: 0,
      expression: "I’m certain",
      phrase: "I’m certain we made the right decision.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 9,
      stage: 0,
      expression: "Would you like",
      phrase: "Would you like a cup of tea?",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 91,
      stage: 0,
      expression: "Do you want",
      phrase: "Do you want tea?",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 92,
      stage: 0,
      expression: "How about",
      phrase: "How about a cup of tea?",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 93,
      stage: 0,
      expression: "You shoud",
      phrase: "You shoud sleep better.",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 94,
      stage: 0,
      expression: "Why don’t you",
      phrase: "Why don’t you come to our party tomorrow? ",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 95,
      stage: 0,
      expression: "If I were you",
      phrase: "If I were you, I would wait for a lawyer.",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 96,
      stage: 0,
      expression: "You’d better",
      phrase: "You’d better take an umbrella.",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 10,
      stage: 0,
      expression: "Bać się",
      phrase: "Boję się podejmowania decyzji",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 61,
      stage: 0,
      expression: "Zmęczyć się",
      phrase: "Myślę, że nie zmęczy się tą podróżą.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 62,
      stage: 0,
      expression: "Śmiać się",
      phrase: "Zawsze się śmiejemy z twoich sucharów.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 63,
      stage: 0,
      expression: "Czuć się",
      phrase: "Czuję się dzisiaj okropnie.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 64,
      stage: 0,
      expression: "Uczyć się",
      phrase: "Ja uczę was polskiego, a wy uczycie się języka polskiego.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 65,
      stage: 0,
      expression: "Szykować się",
      phrase: "Ela szykuje się na randkę.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
  ],
  collectionsList: [
    {
      id: 1,
      name: "Die Kleidung",
      tag: "Deutsch",
    },
    {
      id: 2,
      name: "SIĘ",
      tag: "Polska",
    },
  ],

  extraList: [
    {
      id: 1,
      collectionid: 1,
      side1: "Der Rock",
      side2: "Спідниця",
      tag: "Ihr Rock ist total altmodisch.",
    },
    {
      id: 2,
      collectionid: 1,
      side1: "die Mütze",
      side2: "Шапка",
      tag: "Das ist deine neue Mütze, Schatz.",
    },
    {
      id: 3,
      collectionid: 1,
      side1: "Das Hemd",
      side2: "Сорочка",
      tag: "Mir gefällt dieses Hemd",
    },
    {
      id: 4,
      collectionid: 1,
      side1: "Der Badeanzug",
      side2: "Купальник",
      tag: "Wo finde ich einen Badeanzug?",
    },
    {
      id: 5,
      collectionid: 1,
      side1: "Der Anzug",
      side2: "Костюм",
      tag: "Ich brauche einen Anzug.",
    },
    {
      id: 6,
      collectionid: 1,
      side1: "Das Kleid",
      side2: "Сукня",
      tag: "das Kleid ist rot.",
    },
    {
      id: 7,
      collectionid: 2,
      side1: "Bać się",
      side2: "Боятися",
      tag: "Boję się podejmowania decyzji",
    },
    {
      id: 8,
      collectionid: 2,
      side1: "Zmęczyć się",
      side2: "Втомитися",
      tag: "Myślę, że nie zmęczy się tą podróżą.",
    },
    {
      id: 9,
      collectionid: 2,
      side1: "Śmiać się",
      side2: "Сміятися",
      tag: "Zawsze się śmiejemy z twoich sucharów.",
    },
    {
      id: 10,
      collectionid: 2,
      side1: "Czuć się",
      side2: "Відчувати себе",
      tag: "Czuję się dzisiaj okropnie.",
    },
    {
      id: 11,
      collectionid: 2,
      side1: "Uczyć się",
      side2: "Навчатися",
      tag: "Ja uczę was polskiego, a wy uczycie się języka polskiego.",
    },
    {
      id: 12,
      collectionid: 2,
      side1: "Szykować się",
      side2: "Готуватися",
      tag: "Ela szykuje się na randkę.",
    },
  ],

  publicCollections: [
    {
      id: "p1",
      name: "Gratitude (English)",
      language: "English",
      user: "admin",
    },
    {
      id: "p2",
      name: "Questions (English)",
      language: "English",
      user: "admin",
    },
  ],
  publicExpressions: [
    {
      id: "p11",
      collectionid: "p1",
      expression: "Thank you",
      phrase: "Thank you very much.",
    },
    {
      id: "p12",
      collectionid: "p1",
      expression: "Appreciate ",
      phrase: "I appreciate your help.",
    },
    {
      id: "p13",
      collectionid: "p1",
      expression: "Welcome ",
      phrase: "You’re welcome. Always welcome.",
    },
    {
      id: "p14",
      collectionid: "p1",
      expression: "It’s nothing ",
      phrase: "It’s nothing. Don’t mention it. Not at all",
    },
    {
      id: "p21",
      collectionid: "p2",
      expression: "What is",
      phrase: "What is sarcasm?",
    },
    {
      id: "p22",
      collectionid: "p2",
      expression: "Where are",
      phrase: "Where are your friends when you need them?",
    },
    {
      id: "p23",
      collectionid: "p2",
      expression: "Can I ",
      phrase: "Can I borrow your pen? ",
    },
    {
      id: "p24",
      collectionid: "p2",
      expression: "Can you",
      phrase: "Can you ask your dog to bark, please?",
    },
    {
      id: "p25",
      collectionid: "p2",
      expression: "How much",
      phrase: "How much are your boots, your clothes and your motorcycle? ",
    },
    {
      id: "p26",
      collectionid: "p2",
      expression: "How many",
      phrase: "How many times can you fold a piece of paper? ",
    },
    {
      id: "p26",
      collectionid: "p2",
      expression: "How long",
      phrase: "How long can you hold your breath?",
    },
    {
      id: "p27",
      collectionid: "p2",
      expression: "How do I",
      phrase: "How do I go to the library, please?",
    },
    {
      id: "p27",
      collectionid: "p2",
      expression: "What time",
      phrase: "What time do you close?",
    },
    {
      id: "p28",
      collectionid: "p2",
      expression: "Where can I get",
      phrase: "Where can I get such a nice prom dress? ",
    },
  ],
};
export default dataBase;
