const dataBase = {
  users: [
    {
      id: 1,
      name: "test user",
      email: "test@test.test",
      password: 1,
      sessions: [],
      imgu: "https://firebasestorage.googleapis.com/v0/b/words-d2019.appspot.com/o/avatars%2Fav1.png?alt=media&token=d83bc75a-2744-49c2-b961-93c631c4351f",
    },
  ],
  user: {
    id: "",
    name: "",
  },
  collectionsList: [
    {
      id: 1,
      name: "Die Kleidung (Deutsch)",
    },
    {
      id: 2,
      name: "Certainty (English)",
    },
    {
      id: 3,
      name: "Suggestion (English)",
    },
    {
      id: 4,
      name: "SIĘ (Polska)",
    },
  ],
  wordsList: [
    {
      id: 1,
      collectionid: 1,
      stage: 7,
      word: "Der Rock",
      sentence: "Ihr Rock ist total altmodisch.",
      nextDate: new Date(),
      history: [
        { action: "add", date: new Date("2022-04-20") },
        { action: "read by the plan", date: new Date("2022-04-20") },
        { action: "read by the plan", date: new Date("2022-04-21") },
        { action: "read by the plan", date: new Date("2022-04-22") },
        { action: "read by the plan", date: new Date("2022-04-23") },
        { action: "read by the plan", date: new Date("2022-04-24") },
        { action: "read by the plan", date: new Date("2022-04-25") },
        { action: "read by the plan", date: new Date("2022-04-26") },
      ],
    },
    {
      id: 2,
      collectionid: 1,
      stage: 1,
      word: "die Mütze",
      sentence: "Das ist deine neue Mütze, Schatz.",
      nextDate: new Date("2022-05-01"),
      history: [
        { action: "add", date: new Date("2022-04-30") },
        { action: "read by the plan", date: new Date("2022-04-30") },
      ],
    },
    {
      id: 3,
      collectionid: 1,
      stage: 0,
      word: "Das Hemd",
      sentence: "Mir gefällt dieses Hemd",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 4,
      collectionid: 1,
      stage: 0,
      word: "Der Badeanzug",
      sentence: "Wo finde ich einen Badeanzug?",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 44,
      collectionid: 1,
      stage: 0,
      word: "Der Anzug",
      sentence: "Ich brauche einen Anzug.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 45,
      collectionid: 1,
      stage: 0,
      word: "Das Kleid",
      sentence: "das Kleid ist rot.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 5,
      collectionid: 2,
      stage: 0,
      word: "I think",
      sentence: "I think he is taller than you, but I can’t be certain.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 6,
      collectionid: 2,
      stage: 0,
      word: "I guess",
      sentence: "I guess she prefers roses.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 7,
      collectionid: 2,
      stage: 0,
      word: "Not sure",
      sentence: "I’m not sure we should eat this meal.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 8,
      collectionid: 2,
      stage: 0,
      word: "Not quite sure",
      sentence:
        "Anna explained the task but I’m not quite sure they understood her.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 81,
      collectionid: 2,
      stage: 0,
      word: "Probably",
      sentence: "This is probably the rarest mineral in the world.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 82,
      collectionid: 2,
      stage: 0,
      word: "I’m positive",
      sentence: "I’m positive I left my wallet in my car.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 83,
      collectionid: 2,
      stage: 0,
      word: "I’m certain",
      sentence: "I’m certain we made the right decision.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 9,
      collectionid: 3,
      stage: 0,
      word: "Would you like",
      sentence: "Would you like a cup of tea?",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 91,
      collectionid: 3,
      stage: 0,
      word: "Do you want",
      sentence: "Do you want tea?",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 92,
      collectionid: 3,
      stage: 0,
      word: "How about",
      sentence: "How about a cup of tea?",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 93,
      collectionid: 3,
      stage: 0,
      word: "You shoud",
      sentence: "You shoud sleep better.",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 94,
      collectionid: 3,
      stage: 0,
      word: "Why don’t you",
      sentence: "Why don’t you come to our party tomorrow? ",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 95,
      collectionid: 3,
      stage: 0,
      word: "If I were you",
      sentence: "If I were you, I would wait for a lawyer.",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 96,
      collectionid: 3,
      stage: 0,
      word: "You’d better",
      sentence: "You’d better take an umbrella.",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 10,
      collectionid: 4,
      stage: 0,
      word: "Bać się",
      sentence: "Boję się podejmowania decyzji",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 61,
      collectionid: 4,
      stage: 0,
      word: "Zmęczyć się",
      sentence: "Myślę, że nie zmęczy się tą podróżą.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 62,
      collectionid: 4,
      stage: 0,
      word: "Śmiać się",
      sentence: "Zawsze się śmiejemy z twoich sucharów.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 63,
      collectionid: 4,
      stage: 0,
      word: "Czuć się",
      sentence: "Czuję się dzisiaj okropnie.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 64,
      collectionid: 4,
      stage: 0,
      word: "Uczyć się",
      sentence: "Ja uczę was polskiego, a wy uczycie się języka polskiego.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 65,
      collectionid: 4,
      stage: 0,
      word: "Szykować się",
      sentence: "Ela szykuje się na randkę.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
  ],
  collectionsListExample: [
    {
      id: 1,
      name: "My first collection",
    },
  ],
  wordsListExample: [
    {
      id: 1,
      collectionid: 1,
      stage: 0,
      word: "example",
      sentence: "A sentence for example.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
  ],
  avatars: [
    "https://firebasestorage.googleapis.com/v0/b/words-d2019.appspot.com/o/av1.png?alt=media&token=66a857ae-e129-40f6-9cb4-83cc9eb16d37",
    "https://firebasestorage.googleapis.com/v0/b/words-d2019.appspot.com/o/av2.jpg?alt=media&token=f4af2c02-e974-4fe0-abb9-e61aefa079ed",
    "https://firebasestorage.googleapis.com/v0/b/words-d2019.appspot.com/o/av3.jpg?alt=media&token=b6c0c2c7-2f64-4625-a8f9-abfe053d58a7",
    "https://firebasestorage.googleapis.com/v0/b/words-d2019.appspot.com/o/av4.jpg?alt=media&token=7704c553-f7e4-4447-9309-ae13356a4526",
  ],
};
export default dataBase;
