const dataBase = {
  users: [
    {
      id: 1,
      name: "test user",
      email: "test@test.test",
      password: 1,
      sessions: [],
      imgu: "https://firebasestorage.googleapis.com/v0/b/words-d2019.appspot.com/o/avatars%2Fav1.png?alt=media&token=d83bc75a-2744-49c2-b961-93c631c4351f",
    },
  ],
  user: {
    id: "",
    name: "",
  },
  collectionsList: [
    {
      id: 1,
      name: "Die Kleidung (Deutsch)",
    },
    {
      id: 2,
      name: "Certainty (English)",
    },
    {
      id: 3,
      name: "Suggestion (English)",
    },
    {
      id: 4,
      name: "SIĘ (Polska)",
    },
  ],
  wordsList: [
    {
      id: 1,
      collectionid: 1,
      stage: 7,
      word: "Der Rock",
      sentence: "Ihr Rock ist total altmodisch.",
      nextDate: new Date(),
      history: [
        { action: "add", date: new Date("2022-04-20") },
        { action: "read by the plan", date: new Date("2022-04-20") },
        { action: "read by the plan", date: new Date("2022-04-21") },
        { action: "read by the plan", date: new Date("2022-04-22") },
        { action: "read by the plan", date: new Date("2022-04-23") },
        { action: "read by the plan", date: new Date("2022-04-24") },
        { action: "read by the plan", date: new Date("2022-04-25") },
        { action: "read by the plan", date: new Date("2022-04-26") },
      ],
    },
    {
      id: 2,
      collectionid: 1,
      stage: 1,
      word: "die Mütze",
      sentence: "Das ist deine neue Mütze, Schatz.",
      nextDate: new Date("2022-05-01"),
      history: [
        { action: "add", date: new Date("2022-04-30") },
        { action: "read by the plan", date: new Date("2022-04-30") },
      ],
    },
    {
      id: 3,
      collectionid: 1,
      stage: 0,
      word: "Das Hemd",
      sentence: "Mir gefällt dieses Hemd",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 4,
      collectionid: 1,
      stage: 0,
      word: "Der Badeanzug",
      sentence: "Wo finde ich einen Badeanzug?",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 44,
      collectionid: 1,
      stage: 0,
      word: "Der Anzug",
      sentence: "Ich brauche einen Anzug.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 45,
      collectionid: 1,
      stage: 0,
      word: "Das Kleid",
      sentence: "das Kleid ist rot.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 5,
      collectionid: 2,
      stage: 0,
      word: "I think",
      sentence: "I think he is taller than you, but I can’t be certain.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 6,
      collectionid: 2,
      stage: 0,
      word: "I guess",
      sentence: "I guess she prefers roses.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 7,
      collectionid: 2,
      stage: 0,
      word: "Not sure",
      sentence: "I’m not sure we should eat this meal.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 8,
      collectionid: 2,
      stage: 0,
      word: "Not quite sure",
      sentence:
        "Anna explained the task but I’m not quite sure they understood her.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 81,
      collectionid: 2,
      stage: 0,
      word: "Probably",
      sentence: "This is probably the rarest mineral in the world.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 82,
      collectionid: 2,
      stage: 0,
      word: "I’m positive",
      sentence: "I’m positive I left my wallet in my car.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 83,
      collectionid: 2,
      stage: 0,
      word: "I’m certain",
      sentence: "I’m certain we made the right decision.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 9,
      collectionid: 3,
      stage: 0,
      word: "Would you like",
      sentence: "Would you like a cup of tea?",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 91,
      collectionid: 3,
      stage: 0,
      word: "Do you want",
      sentence: "Do you want tea?",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 92,
      collectionid: 3,
      stage: 0,
      word: "How about",
      sentence: "How about a cup of tea?",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 93,
      collectionid: 3,
      stage: 0,
      word: "You shoud",
      sentence: "You shoud sleep better.",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 94,
      collectionid: 3,
      stage: 0,
      word: "Why don’t you",
      sentence: "Why don’t you come to our party tomorrow? ",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 95,
      collectionid: 3,
      stage: 0,
      word: "If I were you",
      sentence: "If I were you, I would wait for a lawyer.",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 96,
      collectionid: 3,
      stage: 0,
      word: "You’d better",
      sentence: "You’d better take an umbrella.",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 10,
      collectionid: 4,
      stage: 0,
      word: "Bać się",
      sentence: "Boję się podejmowania decyzji",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 61,
      collectionid: 4,
      stage: 0,
      word: "Zmęczyć się",
      sentence: "Myślę, że nie zmęczy się tą podróżą.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 62,
      collectionid: 4,
      stage: 0,
      word: "Śmiać się",
      sentence: "Zawsze się śmiejemy z twoich sucharów.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 63,
      collectionid: 4,
      stage: 0,
      word: "Czuć się",
      sentence: "Czuję się dzisiaj okropnie.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 64,
      collectionid: 4,
      stage: 0,
      word: "Uczyć się",
      sentence: "Ja uczę was polskiego, a wy uczycie się języka polskiego.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 65,
      collectionid: 4,
      stage: 0,
      word: "Szykować się",
      sentence: "Ela szykuje się na randkę.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
  ],
  collectionsListExample: [
    {
      id: 1,
      name: "My first collection",
    },
  ],
  wordsListExample: [
    {
      id: 1,
      collectionid: 1,
      stage: 0,
      word: "example",
      sentence: "A sentence for example.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
  ],

  publicCollections: [
    {
      id: "p1",
      name: "Gratitude (English)",
      language: "English",
      user: "admin",
    },
    {
      id: "p2",
      name: "Questions (English)",
      language: "English",
      user: "admin",
    },
  ],
  publicWords: [
    {
      id: "p11",
      collectionid: "p1",
      word: "Thank you",
      sentence: "Thank you very much.",
    },
    {
      id: "p12",
      collectionid: "p1",
      word: "Appreciate ",
      sentence: "I appreciate your help.",
    },
    {
      id: "p13",
      collectionid: "p1",
      word: "Welcome ",
      sentence: "You’re welcome. Always welcome.",
    },
    {
      id: "p14",
      collectionid: "p1",
      word: "It’s nothing ",
      sentence: "It’s nothing. Don’t mention it. Not at all",
    },
    {
      id: "p21",
      collectionid: "p2",
      word: "What is",
      sentence: "What is sarcasm?",
    },
    {
      id: "p22",
      collectionid: "p2",
      word: "Where are",
      sentence: "Where are your friends when you need them?",
    },
    {
      id: "p23",
      collectionid: "p2",
      word: "Can I ",
      sentence: "Can I borrow your pen? ",
    },
    {
      id: "p24",
      collectionid: "p2",
      word: "Can you",
      sentence: "Can you ask your dog to bark, please?",
    },
    {
      id: "p25",
      collectionid: "p2",
      word: "How much",
      sentence: "How much are your boots, your clothes and your motorcycle? ",
    },
    {
      id: "p26",
      collectionid: "p2",
      word: "How many",
      sentence: "How many times can you fold a piece of paper? ",
    },
    {
      id: "p26",
      collectionid: "p2",
      word: "How long",
      sentence: "How long can you hold your breath?",
    },
    {
      id: "p27",
      collectionid: "p2",
      word: "How do I",
      sentence: "How do I go to the library, please?",
    },
    {
      id: "p27",
      collectionid: "p2",
      word: "What time",
      sentence: "What time do you close?",
    },
    {
      id: "p28",
      collectionid: "p2",
      word: "Where can I get",
      sentence: "Where can I get such a nice prom dress? ",
    },
  ],
};
export default dataBase;
